channels:
 - defaults
dependencies:
 - tabula-py
 - holidays
 - pysimpleguiqt
 - sqlalchemy
 - pytz
 - spyder-kernels
 - pip:
   - google-api-python-client
   - google-auth-httplib2
   - google-auth-oauthlib